"""Training se pehle kam aaega"""

IMAGE_HEIGHT = 83
IMAGE_WIDTH = 100
FRAME_STACK = 4

STATE_SHAPE = (IMAGE_HEIGHT, IMAGE_WIDTH, FRAME_STACK)

NUM_ACTIONS = 3

"""Training ke waqt set krna"""

LEARNING_RATE = 2.5e-5
GAMMA = 0.99
BATCH_SIZE = 32
REPLAY_BUFFER_SIZE = 50000

EPSILON_START = 1.0
EPSILON_MIN = 0.01
EPSILON_DECAY = 0.997

TARGET_UPDATE_FREQUENCY = 5


