"""Training se pehle kam aaega"""

IMAGE_HEIGHT = 83
IMAGE_WIDTH = 100
FRAME_STACK = 4

STATE_SHAPE = (IMAGE_HEIGHT, IMAGE_WIDTH, FRAME_STACK)

NUM_ACTIONS = 3

"""Training ke waqt set krna"""

LEARNING_RATE = 1e-4
GAMMA = 0.99
BATCH_SIZE = 32
REPLAY_BUFFER_SIZE = 50000

EPSILON_START = 0.1
EPSILON_MIN = 0.0001
EPSILON_DECAY = 0.99995

TARGET_UPDATE_FREQUENCY = 5


